apiVersion: v1
kind: Service
metadata:
  name: ecommerce-redis
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: ecommerce-redis
  ports:
  - name: ecommerce-redis
    port: 6379
    targetPort: 6379