apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-queue
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce-queue
  template:
    metadata:
      labels:
        app: ecommerce-queue
    spec:
      containers:
      - name: ecommerce-queue
        image: rabbitmq:3.13-rc-management-alpine
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: username
        - name: RABBITMQ_DEFAULT_PASS
          value: password
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: queue
          containerPort: 5672
          protocol: TCP
        - name: mgmt
          containerPort: 15672
          protocol: TCP
        