apiVersion: v1
kind: Service
metadata:
  name: ecommerce-mysql
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: ecommerce-mysql
  ports:
  - name: ecommerce-mysql
    port: 3306
    targetPort: 3306