apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-backend-secret
  namespace: production
type: Opaque
data:
 # echo -n <secret> | base64
  secret-key-one: NDY1ZTEyOTkxODI5NTEwMDZjYjVkZWI5ZWJlNjU1MTY=
  secret-key-two: YjkwMDNiMzk2ZmY0YmQ5N2FjNmRkNjZhMTc2OTgxZDc=
  gateway-jwt-token: YjZiOTcwMDFjYjFkM2JlYjI1ZjFkOTcyNmM3NTQ2ZTI=
  jwt-token: MmIzMTE1NmJhZGVmNDMyOGM4MjAzODRlZjNiMzFmNDk=
  ecommerce-redis-host: ''
  sender-email: bXlhaC5hdWZkZXJoYXI0M0BldGhlcmVhbC5lbWFpbA==
  sender-email-password: Q2NVdkdienNTNUFxUW5WTlFu
  ecommerce-mysql-db: bXlzcWw6Ly9lY29tbWVyY2VhZG1pbjpwYXNzd29yZEBlY29tbWVyY2UtYXV0aC5jZDh5bWk2b2diN2oudXMtZWFzdC0yLnJkcy5hbWF6b25hd3MuY29tL2Vjb21tZXJjZV9hdXRo

  ecommerce-postgres-host: ZWNvbW1lcmNlLWF1dGgtcG9zdGdyZXMuY2Q4eW1pNm9nYjdqLnVzLWVhc3QtMi5yZHMuYW1hem9uYXdzLmNvbQ==

  ecommerce-postgres-user: ZWNvbW1lcmNlYWRtaW4=
  ecommerce-postgres-password: cGFzc3dvcmQ=
  cloud-name: ZGNodnZnZmFh
  cloud-api-key: MTUyMzg4MTI2Nzc4Mzk2
  cloud-api-secret: eVRrbGhUNEVTQzR1S3ZDaFNGczVfMlBPUU9z
  mongo-database-url: ''
  stripe-api-key: c2tfdGVzdF81MVE5V1JDMDJiSEdXdzREcGhNb25yZFpXaFozY0xOaWJCMHI3R1JTUFQyVk9tZFJ0ZjFCejkzUllnM0IweU1aRFRpR1VBdTc4SmlLcTRxcWRFbDAzVVF6VDAwTGNVZHcyMHg=
  stripe-client-key: ""
  ecommerce-rabbitmq-user: dXNlcm5hbWU=
  ecommerce-rabbitmq-password: cGFzc3dvcmQ=
  ecommerce-rabbitmq-endpoint: YW1xcDovL3VzZXJuYW1lOnBhc3N3b3JkQGVjb21tZXJjZS1xdWV1ZS5wcm9kdWN0aW9uLnN2Yy5jbHVzdGVyLmxvY2FsOjU2NzI=
  ecommerce-elasticsearch-url: aHR0cDovL2VsYXN0aWM6cGFzc3dvcmRAZWNtcmMtZWxhc3RpYy5wcm9kdWN0aW9uLnN2Yy5jbHVzdGVyLmxvY2FsOjkyMDA=
  ecommerce-elastic-apm-server-url: ""
  ecommerce-elastic-apm-secret-token: ""
  ecommerce-elasticsearch-host: ZWNtcmMtZWxhc3RpYy5wcm9kdWN0aW9uLnN2Yy5jbHVzdGVyLmxvY2Fs
  ecommerce-elasticsearch-username: dXNlcm5hbWU=
  ecommerce-elasticsearch-password: cGFzc3dvcmQ=

# To decode: echo -n <encoded-secret> | base64 --docode
