apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-backend-secret
  namespace: production
type: Opaque
data:
 # echo -n <secret> | base64
  secret-key-one: NDY1ZTEyOTkxODI5NTEwMDZjYjVkZWI5ZWJlNjU1MTY=
  secret-key-two: YjkwMDNiMzk2ZmY0YmQ5N2FjNmRkNjZhMTc2OTgxZDc=
  gateway-jwt-token: YjZiOTcwMDFjYjFkM2JlYjI1ZjFkOTcyNmM3NTQ2ZTI=
  jwt-token: MmIzMTE1NmJhZGVmNDMyOGM4MjAzODRlZjNiMzFmNDk=
  # redis host: redis://<redis-primary-key>:6379
  ecommerce-redis-host: cmVkaXM6Ly9lY29tbWVyY2UtcmVkaXMtY2x1c3Rlci5neWVjOXEubmcuMDAwMS51c2UyLmNhY2hlLmFtYXpvbmF3cy5jb206NjM3OQ==
  sender-email: bXlhaC5hdWZkZXJoYXI0M0BldGhlcmVhbC5lbWFpbA==
  sender-email-password: Q2NVdkdienNTNUFxUW5WTlFu
  ecommerce-mysql-db: bXlzcWw6Ly9lY29tbWVyY2VhZG1pbjpwYXNzd29yZEBlY29tbWVyY2UtYXV0aC5jZDh5bWk2b2diN2oudXMtZWFzdC0yLnJkcy5hbWF6b25hd3MuY29tL2Vjb21tZXJjZV9hdXRo
  ecommerce-postgres-host: ZWNvbW1lcmNlLWF1dGgtcG9zdGdyZXMuY2Q4eW1pNm9nYjdqLnVzLWVhc3QtMi5yZHMuYW1hem9uYXdzLmNvbQ==
  ecommerce-postgres-user: ZWNvbW1lcmNlYWRtaW4=
  ecommerce-postgres-password: cGFzc3dvcmQ=
  cloud-name: ZGNodnZnZmFh
  cloud-api-key: MTUyMzg4MTI2Nzc4Mzk2
  cloud-api-secret: eVRrbGhUNEVTQzR1S3ZDaFNGczVfMlBPUU9z
  mongo-database-url: ''
  stripe-api-key: c2tfdGVzdF81MVE5V1JDMDJiSEdXdzREcGhNb25yZFpXaFozY0xOaWJCMHI3R1JTUFQyVk9tZFJ0ZjFCejkzUllnM0IweU1aRFRpR1VBdTc4SmlLcTRxcWRFbDAzVVF6VDAwTGNVZHcyMHg=
  stripe-client-key: ""
  ecommerce-rabbitmq-user: dXNlcm5hbWU=
  ecommerce-rabbitmq-password: cGFzc3dvcmQ=
  ecommerce-rabbitmq-endpoint: YW1xcDovL3VzZXJuYW1lOnBhc3N3b3JkQGVjb21tZXJjZS1xdWV1ZS5wcm9kdWN0aW9uLnN2Yy5jbHVzdGVyLmxvY2FsOjU2NzI=
  ecommerce-elasticsearch-url: aHR0cHM6Ly9lbGFzdGljOjZ5dXVwdXBJdlp5dDZxVnVTdFJBRndNbkBhN2IyZGZiNmQ0NTM0NzdmOGNmOTAxNzE0MTYzZmE2MC51cy1jZW50cmFsMS5nY3AuY2xvdWQuZXMuaW8=
  ecommerce-elastic-apm-server-url: aHR0cHM6Ly9kNmY3NGQ2MjE1Mzg0MDk3YWUyNThjY2Q5MzRiNGE1Ni5hcG0udXMtY2VudHJhbDEuZ2NwLmNsb3VkLmVzLmlvOjQ0Mw==
  ecommerce-elastic-apm-secret-token: ZTJzZzN0U0tSb25HQlRBa1Nk
  ecommerce-elasticsearch-host: ZWNtcmMtZWxhc3RpYy5wcm9kdWN0aW9uLnN2Yy5jbHVzdGVyLmxvY2Fs
  ecommerce-elasticsearch-username: ZWxhc3RpYw==
  ecommerce-elasticsearch-password: Nnl1dXB1cEl2Wnl0NnFWdVN0UkFGd01u
  ecommerce-elastic-cloud-id: YTdiMmRmYjZkNDUzNDc3ZjhjZjkwMTcxNDE2M2ZhNjA=
  # cloud auth: <elasticsearch-username>:<elasticsearch-password>
  ecommerce-elastic-cloud-auth: ZWxhc3RpYzo2eXV1cHVwSXZaeXQ2cVZ1U3RSQUZ3TW4=

# To decode: echo -n <encoded-secret> | base64 --docode
