apiVersion: v1
kind: Service
metadata:
  name: ecommerce-order
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: ecommerce-order
  ports:
  - name: order
    port: 4006
    targetPort: 4006
    protocol: TCP