apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-auth
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecommerce-auth
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: ecommerce-auth
    spec:
      containers:
      - name: ecommerce-auth
        image: mitratech/ecommerce-auth:stable
        imagePullPolicy: Always
        resources:
          limits:
            cpu: '0.5'
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 150Mi
        ports:
        - name: auth
          containerPort: 4002
        env:
          - name: ENABLE_APM
            value: '1'
          - name: NODE_ENV
            value: 'production'
          - name: GATEWAY_JWT_TOKEN
            valueFrom:
              secretKeyRef:
                name: ecommerce-backend-secret
                key: gateway-jwt-token
          - name: JWT_TOKEN
            valueFrom:
              secretKeyRef:
                name: ecommerce-backend-secret
                key: jwt-token
          - name: RABBITMQ_ENDPOINT
            valueFrom:
              secretKeyRef:
                name: ecommerce-backend-secret
                key: ecommerce-rabbitmq-endpoint
          - name: MYSQL_DB
            valueFrom:
              secretKeyRef:
                name: ecommerce-backend-secret
                key: ecommerce-mysql-db
          - name: CLOUD_NAME
            valueFrom:
              secretKeyRef:
                name: ecommerce-backend-secret
                key: cloud-name
          - name: CLOUD_API_KEY
            valueFrom:
              secretKeyRef:
                name: ecommerce-backend-secret
                key: cloud-api-key
          - name: CLOUD_API_SECRET
            valueFrom:
              secretKeyRef:
                name: ecommerce-backend-secret
                key: cloud-api-secret
          - name: CLIENT_URL
            value: 'https://api.ecommerceapp.xyz'
          - name: API_GATEWAY_URL
            value: 'http://ecommerce-gateway.production.svc.cluster.local:4000'
          - name: ELASTIC_SEARCH_URL
            valueFrom:
              secretKeyRef:
                name: ecommerce-backend-secret
                key: ecommerce-elasticsearch-url
          - name: ELASTIC_APM_SERVER_URL
            valueFrom:
              secretKeyRef:
                name: ecommerce-backend-secret
                key:  ecommerce-elastic-apm-server-url
          - name: ELASTIC_APM_SECRET_TOKEN
            valueFrom:
              secretKeyRef:
                name: ecommerce-backend-secret
                key: ecommerce-elastic-apm-secret-token
