apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-backend-secret
  namespace: production
type: Opaque
data:
 # echo -n <secret> | base64
  secret-key-one: NDY1ZTEyOTkxODI5NTEwMDZjYjVkZWI5ZWJlNjU1MTY=
  secret-key-two: YjkwMDNiMzk2ZmY0YmQ5N2FjNmRkNjZhMTc2OTgxZDc=
  gateway-jwt-token: YjZiOTcwMDFjYjFkM2JlYjI1ZjFkOTcyNmM3NTQ2ZTI=
  jwt-token: MmIzMTE1NmJhZGVmNDMyOGM4MjAzODRlZjNiMzFmNDk=
  ecommerce-redis-host: cmVkaXM6Ly86dGhpc2lzbXlvd25wYXNzd29yZDEyM0BAZWNvbW1lcmNlLXJlZGlzLnByb2R1Y3Rpb24uc3ZjLmNsdXN0ZXIubG9jYWw6NjM3OQ==
  sender-email: bXlhaC5hdWZkZXJoYXI0M0BldGhlcmVhbC5lbWFpbA==
  sender-email-password: Q2NVdkdienNTNUFxUW5WTlFu
  ecommerce-mysql-db: bXlzcWw6Ly9lY29tbWVyY2U6YXBpQGVjb21tZXJjZS1teXNxbC5wcm9kdWN0aW9uLnN2Yy5jbHVzdGVyLmxvY2FsOjMzMDYvZWNvbW1lcmNlX2F1dGg=
  ecommerce-postgres-host: 
  ecommerce-postgres-user: 
  ecommerce-postgres-password: 
  cloud-name: 
  cloud-api-key: 
  cloud-api-secret: 
  mongo-database-url: bW9uZ29kYjovL2Vjb21tZXJjZS1tb25nby5wcm9kdWN0aW9uLnN2Yy5jbHVzdGVyLmxvY2FsOjI3MDE3L2Vjb21tZXJjZQ==
  stripe-api-key: 
  stripe-client-key: 
  ecommerce-rabbitmq-user: 
  ecommerce-rabbitmq-password: 
  ecommerce-rabbitmq-endpoint: 
  ecommerce-elasticsearch-url: 
  ecommerce-elastic-apm-server-url: 
  ecommerce-elastic-apm-secret-token: 
  ecommerce-elasticsearch-host: 
  ecommerce-elasticsearch-username: 
  ecommerce-elasticsearch-password: 


















  mongodb://ecommerce-mongo.production.svc.cluster.local:27017/ecommerce