apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-backend-secret
  namespace: production
type: Opaque
data:
 # echo -n <secret> | base64
  secret-key-one: NDY1ZTEyOTkxODI5NTEwMDZjYjVkZWI5ZWJlNjU1MTY=
  secret-key-two: YjkwMDNiMzk2ZmY0YmQ5N2FjNmRkNjZhMTc2OTgxZDc=
  gateway-jwt-token: YjZiOTcwMDFjYjFkM2JlYjI1ZjFkOTcyNmM3NTQ2ZTI=
  jwt-token: MmIzMTE1NmJhZGVmNDMyOGM4MjAzODRlZjNiMzFmNDk=
  ecommerce-redis-host: cmVkaXM6Ly86dGhpc2lzbXlvd25wYXNzd29yZDEyM0BAZWNvbW1lcmNlLXJlZGlzLnByb2R1Y3Rpb24uc3ZjLmNsdXN0ZXIubG9jYWw6NjM3OQ==
  sender-email: bXlhaC5hdWZkZXJoYXI0M0BldGhlcmVhbC5lbWFpbA==
  sender-email-password: Q2NVdkdienNTNUFxUW5WTlFu
  ecommerce-mysql-db: bXlzcWw6Ly9lY29tbWVyY2U6YXBpQGVjb21tZXJjZS1teXNxbC5wcm9kdWN0aW9uLnN2Yy5jbHVzdGVyLmxvY2FsOjMzMDYvZWNvbW1lcmNlX2F1dGg=
  ecommerce-postgres-host: ZWNvbW1lcmNlLXBvc3RncmVzLnByb2R1Y3Rpb24uc3ZjLmNsdXN0ZXIubG9jYWw=
  ecommerce-postgres-user: ZWNvbW1lcmNl
  ecommerce-postgres-password: YXBp
  cloud-name: ZGNodnZnZmFh
  cloud-api-key: MTUyMzg4MTI2Nzc4Mzk2
  cloud-api-secret: eVRrbGhUNEVTQzR1S3ZDaFNGczVfMlBPUU9z
  mongo-database-url: bW9uZ29kYjovL2Vjb21tZXJjZS1tb25nby5wcm9kdWN0aW9uLnN2Yy5jbHVzdGVyLmxvY2FsOjI3MDE3L2Vjb21tZXJjZQ==
  stripe-api-key: c2tfdGVzdF81MVE5V1JDMDJiSEdXdzREcGhNb25yZFpXaFozY0xOaWJCMHI3R1JTUFQyVk9tZFJ0ZjFCejkzUllnM0IweU1aRFRpR1VBdTc4SmlLcTRxcWRFbDAzVVF6VDAwTGNVZHcyMHg=
  stripe-client-key: ""
  ecommerce-rabbitmq-user: dXNlcm5hbWU=
  ecommerce-rabbitmq-password: cGFzc3dvcmQ=
  ecommerce-rabbitmq-endpoint: YW1xcDovL3VzZXJuYW1lOnBhc3N3b3JkQGVjb21tZXJjZS1xdWV1ZS5wcm9kdWN0aW9uLnN2Yy5jbHVzdGVyLmxvY2FsOjU2NzI=
  ecommerce-elasticsearch-url: aHR0cDovL2VsYXN0aWM6cGFzc3dvcmRAZWNtcmMtZWxhc3RpYy5wcm9kdWN0aW9uLnN2Yy5jbHVzdGVyLmxvY2FsOjkyMDA=
  ecommerce-elastic-apm-server-url: ""
  ecommerce-elastic-apm-secret-token: ""
  ecommerce-elasticsearch-host: ZWNtcmMtZWxhc3RpYy5wcm9kdWN0aW9uLnN2Yy5jbHVzdGVyLmxvY2Fs
  ecommerce-elasticsearch-username: dXNlcm5hbWU=
  ecommerce-elasticsearch-password: cGFzc3dvcmQ=

# To decode: echo -n <encoded-secret> | base64 --docode
