apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecmrc-kibana
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecmrc-kibana
  template:
    metadata:
      labels:
        app: ecmrc-kibana
    spec:
      containers:
        - name: ecmrc-kibana
          image: docker.elastic.co/kibana/kibana:8.14.1
          resources:
            limits:
              memory: "1Gi"
              cpu: "1500m"
            requests:
              cpu: 250m
              memory: 1Gi
          ports:
          - name: ecmrc-kibana
            containerPort: 5601
          env:
            - name: ELASTICSEARCH_HOSTS
              # http://<service-name>.<namespace>.svc.cluster.local:<port-number>
              value: http://ecmrc-elastic.production.svc.cluster.local:9200
            - name: ELASTICSEARCH_USERNAME
              value: kibana_system
            - name: ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ecommerce-backend-secret
                  key: ecommerce-elasticsearch-password
            - name: ELASTICSEARCH_SERVICEACCOUNT_TOKEN
              value: AAEAAWVsYXN0aWMva2liYW5hL2Vjb21tZXJjZS1raWJhbmE6b1VabXc0SEFSZDZZUlZ0b0lmUUo3dw
          volumeMounts:
            - name: kibana-config
              mountPath: /usr/share/kibana/config
      volumes:
      - name: kibana-config
        configMap:
          name: kibana-config