apiVersion: v1
kind: ServiceAccount
metadata:
  name: metricbeat
  namespace: production
  labels:
    k8s-app: metricbeat
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metricbeat
  labels:
    k8s-app: metricbeat
rules:
- apiGroups: [""]
  resources:
  - nodes
  - namespaces
  - events
  - pods
  - services
  - persistentvolumes
  - persistentvolumeclaims
  verbs: ["get", "list", "watch"]
# Enable this rule only if planing to use Kubernetes keystore
#- apiGroups: [""]
#  resources:
#  - secrets
#  verbs: ["get"]
- apiGroups: ["extensions"]
  resources:
  - replicasets
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources:
  - statefulsets
  - deployments
  - replicasets
  - daemonsets
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["get", "list", "watch"]
- apiGroups: ["storage.k8s.io"]
  resources:
    - storageclasses
  verbs: ["get", "list", "watch"]
- apiGroups:
  - ""
  resources:
  - nodes/stats
  verbs:
  - get
- nonResourceURLs:
  - "/metrics"
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: metricbeat
  # should be the namespace where metricbeat is running
  namespace: production
  labels:
    k8s-app: metricbeat
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs: ["get", "create", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: metricbeat-kubeadm-config
  namespace: production
  labels:
    k8s-app: metricbeat
rules:
  - apiGroups: [""]
    resources:
      - configmaps
    resourceNames:
      - kubeadm-config
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metricbeat
subjects:
- kind: ServiceAccount
  name: metricbeat
  namespace: production
roleRef:
  kind: ClusterRole
  name: metricbeat
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: metricbeat
  namespace: production
subjects:
  - kind: ServiceAccount
    name: metricbeat
    namespace: production
roleRef:
  kind: Role
  name: metricbeat
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: metricbeat-kubeadm-config
  namespace: production
subjects:
  - kind: ServiceAccount
    name: metricbeat
    namespace: production
roleRef:
  kind: Role
  name: metricbeat-kubeadm-config
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: metricbeat-daemonset-config
  namespace: production
  labels:
    k8s-app: metricbeat
data:
  metricbeat.yml: |-
    metricbeat.config:
    modules:
      path: ${path.config}/modules.d/*.yml
      # Reload module configs as they change:
      reload.enabled: false

    metricbeat.autodiscover:
      providers:
        - type: docker
          hints.enabled: true

    metricbeat.modules:
    - module: docker
      metricsets:
        - "container"
        - "cpu"
        - "diskio"
        - "healthcheck"
        - "info"
        - "memory"
        - "network"
      hosts: ["unix:///var/run/docker.sock"]
      period: 10s
      enabled: true

    - module: system
      metricsets:
        - cpu             # CPU usage
        - load            # CPU load averages
        - memory          # Memory usage
        - network         # Network IO
        - process         # Per process metrics
        - process_summary # Process summary
        - uptime          # System Uptime
        - socket_summary  # Socket summary
        - core            # Per CPU core usage
        - diskio          # Disk IO
        - filesystem      # File system usage for each mountpoint
        - fsstat          # File system summary metrics
        - socket          # Sockets and connection info (linux only)
      enabled: true
      period: 10s
      processes: ['.*']
      hostfs: "/hostfs"
      cpu.metrics:  ["percentages","normalized_percentages"]
      core.metrics: ["percentages"]

    - module: rabbitmq
      metricsets: ["node", "queue", "connection", "exchange", "shovel"]
      enabled: true
      period: 10s
      hosts: ["127.0.0.1:15672"]

    - module: mongodb
      metricsets: ["dbstats", "status", "collstats", "metrics", "replstatus"]
      period: 10s
      enabled: true
      # The hosts must be passed as MongoDB URLs in the format:
      # [mongodb://][user:pass@]host[:port].
      # The username and password can also be set using the respective configuration
      # options. The credentials in the URL take precedence over the username and
      # password configuration options.
      hosts: ["mongodb://127.0.0.1:27017"]

    - module: mysql
      metricsets:
        - status
        - performance
      period: 10s
      hosts: ["tcp(127.0.0.1:3306)/"]
      username: ecommerce
      password: api

    - module: postgresql
      enabled: true
      metricsets:
        - database
        - bgwriter
        - activity

      period: 10s
      hosts: ["postgres://127.0.0.1:5432"]
      username: ecommerce
      password: api

    processors:
      - add_cloud_metadata: ~

    # cloud.id: ${ELASTIC_CLOUD_ID}
    # cloud.auth: ${ELASTIC_CLOUD_AUTH}

    output.elasticsearch:
      hosts: ['${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}']
      username: ${ELASTICSEARCH_USERNAME}
      password: ${ELASTICSEARCH_PASSWORD}

---
